import {safeURL,dateOnly,stageClaim as publicClaim} from './map-data.js';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={projects:['Projects','פרויקטים'],plans:['Planning records','תוכניות'],candidates:['Areas for investigation','אזורים לבדיקה']};
const stageHe={construction:'בבנייה',permitting_procurement:'היתרים ורכש',planning:'בתכנון',permits_procurement:'היתרים ורכש',operational:'פעיל',under_construction:'בבנייה',planned:'מתוכנן',unknown:'לא ידוע',pilot_operational:'פיילוט פעיל',commissioned:'הופעל',announced:'הוכרז',research_pilot:'פיילוט מחקר'};
const sourceLink=(url,name)=>{const href=safeURL(url);return href?'<a href="'+e(href)+'" target="_blank" rel="noopener noreferrer">'+e(name)+' ↗</a>':e(name);};
export function detailHTML(r,registry,lang){const t=(en,he)=>lang==='he'?he:en;let body=`<span class="tag">${labels[r.layer][lang==='he'?1:0]}</span><h2 id="detail-title">${e(lang==='he'?r.nameHe||r.name:r.name)}</h2><div class="detail-meta"><div><span>${t('Locality','יישוב')}</span><strong>${e(r.locality||t('Not stated','לא צוין'))}</strong></div><div><span>${t('District','מחוז')}</span><strong>${e(r.district||t('Not stated','לא צוין'))}</strong></div></div>`;
 if(r.layer==='projects'){const p=r.raw,c=publicClaim(p);body+=`<p>${e(p.summary)}</p>${lang==='he'?`<p class="minor">תקציר הראיות המיובא נשמר באנגלית; שמות ומקורות מוצגים כפי שפורסמו.</p>`:''}<div class="method-note">${t('Reported stage','השלב המדווח')}: <strong>${e(lang==='he'?stageHe[c?.value?.code]||c?.value?.label:c?.value?.label||'Unknown')}</strong><br>${t('Record reviewed','הרשומה נבדקה')}: ${e(c?.checkedAt||'—')}<br>${t('Observation dated','תאריך התצפית')}: ${e(c?.observedAt||t('Unknown','לא ידוע'))}</div><h3>${t('Organizations','ארגונים')}</h3>${p.organizations.map(o=>`<p>${e(o.name)} — ${e(o.role.replaceAll('_',' '))}</p>`).join('')}<h3>${t('Evidence and limitations','ראיות ומגבלות')}</h3>${p.claims.map(c=>`<div class="evidence"><strong>${e(c.property.replaceAll('_',' '))}</strong><p>${e(c.explanation)}</p><p>${e(c.evidenceStatus)} · ${e(c.checkedAt)}</p>${(c.evidence||[]).map(ev=>{const s=registry.sources.find(s=>s.sourceId===ev.sourceId);return s?`<p>${sourceLink(s.url,lang==='he'?s.originalTitle||s.title:s.title)}</p>`:''}).join('')}</div>`).join('')}`;}
 else if(r.layer==='plans'){body+=`<div class="detail-meta"><div><span>${t('Plan number','מספר תוכנית')}</span><strong>${e(r.planNumber)}</strong></div><div><span>${t('Official planning status (Hebrew)','סטטוס תכנוני רשמי')}</span><strong>${e(r.stage)}</strong></div><div><span>${t('Proposed area / dunam','שטח מוצע / דונם')}</span><strong>${Number(r.area).toLocaleString(lang,{maximumFractionDigits:1})}</strong></div><div><span>${t('Status date','תאריך הסטטוס')}</span><strong>${dateOnly(r.date)||'—'}</strong></div></div><p class="method-note">${t('This is an official planning record. It does not establish construction or operation. Names and statuses retain the official Hebrew text.','זו רשומת תכנון רשמית. היא אינה מעידה על הקמה או הפעלה. השמות והסטטוסים נשמרו בנוסח העברי הרשמי.')}</p>${sourceLink(r.url,t('Open official planning record','לרשומת התכנון הרשמית'))}`;}
 else{body+=`<div class="detail-meta"><div><span>${t('Crop','גידול')}</span><strong>${e(r.raw.crop)}</strong></div><div><span>${t('Area / dunam','שטח / דונם')}</span><strong>${e(r.raw.areaDunam)}</strong></div></div><p class="method-note">${t('This parcel is a screening candidate from a 500-parcel sample. Technical suitability, ownership consent, permits and grid connection have not been established. A ranking score is not a feasibility assessment.','זו חלקה מועמדת לבדיקה מתוך מדגם של 500 חלקות. לא אושרו התאמה טכנית, הסכמת בעלים, היתרים או חיבור לרשת. ציון דירוג אינו בדיקת היתכנות.')}</p>${sourceLink(r.url,t('View source dataset','למערך נתוני המקור'))}`;}
 return body;}
