// Public record contracts shared by the interface and regression tests.
export const layerNames = ['projects','plans','candidates','industrial','public'];
export const districtLabels = {north:['Northern','צפון'],south:['Southern','דרום'],haifa:['Haifa','חיפה'],jerusalem:['Jerusalem','ירושלים'],central:['Central','מרכז'],telaviv:['Tel Aviv','תל אביב']};
export const stageLabels = {operating:['Operating','פעיל'],construction:['Under construction','בבנייה'],planning:['In planning','בתכנון'],permitting:['Permits & procurement','היתרים ורכש'],research:['Research pilot','פיילוט מחקר'],announced:['Announced','הוכרז'],hold:['On hold','בהשהיה'],cancelled:['Cancelled','בוטל'],unknown:['Not established','לא נקבע']};
export const publicClaims = p => (p.claims||[]).filter(c=>c.visibility==='public'&&c.editorialState==='published');
export const stageClaim = p => publicClaims(p).find(c=>c.property==='actual_implementation_stage');
export function safeURL(value,base) { if(!value)return null;try {const u=new URL(value,base);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;} }
export function dateOnly(value) {if(value==null||value==='')return null;const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString().slice(0,10);}
export function normalizeSearch(value){return String(value??'').normalize('NFKC').toLowerCase().replace(/[\u0591-\u05c7]/g,'').replace(/[’'"״׳-]/g,' ').replace(/\s+/g,' ').trim();}
export function districtKeys(value){return String(value||'').split(',').map(s=>s.trim()).filter(Boolean).map(s=>{const n=normalizeSearch(s);if(/north|צפון/.test(n))return 'north';if(/south|negev|דרום|נגב/.test(n))return 'south';if(/haifa|חיפה/.test(n))return 'haifa';if(/jerusalem|ירושלים/.test(n))return 'jerusalem';if(/central|center|מרכז/.test(n))return 'central';if(/tel aviv|תל אביב/.test(n))return 'telaviv';return s;}).filter((s,i,a)=>a.indexOf(s)===i);}
export function stageKey(code){return ({operational:'operating',pilot_operational:'operating',commissioned:'operating',under_construction:'construction',construction:'construction',planning:'planning',planned:'planning',permitting_procurement:'permitting',permits_procurement:'permitting',research_pilot:'research',announced:'announced',on_hold:'hold',cancelled:'cancelled'})[code]||'unknown';}
function point(p){return Array.isArray(p)&&p.length>=2&&Number.isFinite(p[0])&&Number.isFinite(p[1])&&Math.abs(p[0])<=180&&Math.abs(p[1])<=90;}
function ring(r){return Array.isArray(r)&&r.length>=4&&r.every(point)&&r[0][0]===r.at(-1)[0]&&r[0][1]===r.at(-1)[1];}
export function validGeometry(g){if(!g)return false;if(g.type==='Point')return point(g.coordinates);const polygon=p=>Array.isArray(p)&&p.length>0&&p.every(ring);return g.type==='Polygon'?polygon(g.coordinates):g.type==='MultiPolygon'&&Array.isArray(g.coordinates)&&g.coordinates.length>0&&g.coordinates.every(polygon);}
const field=(p,n)=>p['AGRO_csv_'+n];
export function normalizeDataset(name,data){
 if(['provenance','potential','outcomes','spatial'].includes(name)){if(!data||typeof data!=='object'||Array.isArray(data))throw Error('Invalid provenance');if(name==='potential'&&(!data.summary||!Array.isArray(data.sources)||!data.officialMethod))throw Error('Invalid potential');if(name==='outcomes'&&!Array.isArray(data.projects))throw Error('Invalid outcomes');if(name==='spatial'&&!Array.isArray(data.records))throw Error('Invalid spatial');return {data,records:[],rejected:0};}
 const input=name==='projects'?data?.projects:data?.features;if(!Array.isArray(input)||name==='projects'&&!Array.isArray(data.sources))throw Error('Invalid dataset');
 const records=[];let rejected=0,duplicates=0;const ids=new Set(),signatures=new Map();
 for(const item of input){try{let r;if(name==='projects') {if(item.publicationState!=='published')continue;const c=stageClaim(item);r={id:item.projectId,layer:name,name:item.name,nameHe:item.nameOriginal,locality:item.site?.locality,district:item.site?.district,stage:c?.value?.label,stageKey:stageKey(c?.value?.code),geometry:item.site?.centroid?{type:'Point',coordinates:item.site.centroid}:null,raw:{...item,claims:publicClaims(item)}};}
 else if(name==='plans'){const p=item.properties;if(!p)throw Error();const id=field(p,'מספר_תכנית_ראשי');if(id==null)throw Error();r={id:'plan-'+id,layer:name,name:field(p,'שם_תכנית'),locality:field(p,'ישובים'),district:field(p,'מחוזות'),planNumber:field(p,'מספר_תכנית'),stage:field(p,'סטטוס_דשבורד'),date:dateOnly(field(p,'תאריך_עדכון_סטטוס')),area:field(p,'סהכ_מוצע'),url:safeURL(field(p,'קישור_לתכנית')),geometry:item.geometry};}
 else if(['candidates','industrial','public'].includes(name)){const p=item.properties;if(!p)throw Error();r={id:p.candidateId,layer:name,name:p.name,locality:p.locality,district:p.district,url:safeURL(p.sourceUrl),geometry:item.geometry,raw:p};}else throw Error('Unknown layer');
 if(ids.has(r.id)&&signatures.get(r.id)===JSON.stringify(item)){duplicates++;continue;}if(!r.id||!r.name||ids.has(r.id))throw Error();ids.add(r.id);signatures.set(r.id,JSON.stringify(item));r.districtKeys=districtKeys(r.district);r.geometryValid=validGeometry(r.geometry);r.extent=r.geometryValid?geometryExtent(r.geometry):null;records.push(r);
 }catch{rejected++;}}
 if(input.length&&!records.length&&rejected)throw Error('No readable records');return {data,records,rejected,duplicates};
}
export async function loadDataset(name,fetcher=fetch){const response=await fetcher(`./data/${name}.json`,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Data unavailable');return normalizeDataset(name,await response.json());}
export async function loadDatasets(names,fetcher=fetch,onResult=()=>{}){return Promise.all(names.map(async name=>{let result;try{result={name,status:'ready',...await loadDataset(name,fetcher)};}catch{result={name,status:'error',records:[],rejected:0};}onResult(result);return result;}));}
export function readState(search){const p=new URLSearchParams(search);const b=p.get('bounds')?.split(',').map(Number);const bounds=b?.length===4&&b.every(Number.isFinite)&&b[0]>=-180&&b[2]<=180&&b[1]>=-90&&b[3]<=90&&b[0]<b[2]&&b[1]<b[3]?b:null;return {...(p.get('category')?{category:p.get('category')}:{}),...(bounds?{bounds}:{}),lang:p.get('lang')==='he'?'he':'en',layer:layerNames.includes(p.get('layer'))?p.get('layer'):'projects',query:p.get('q')||'',district:p.get('district')||'',stage:p.get('stage')||'',record:p.get('record')||'',view:p.get('view')==='list'?'list':'map'};}
export function stateURL(base,state){const u=new URL(base);for(const k of ['lang','layer','q','district','stage','record','view','bounds','category'])u.searchParams.delete(k);u.searchParams.set('lang',state.lang);u.searchParams.set('layer',state.layer);for(const [key,value] of Object.entries({category:state.category,bounds:state.bounds?.join(','),q:state.query,district:state.district,stage:state.layer==='projects'?state.stage:'',record:state.record,view:state.view==='list'?'list':''}))if(value)u.searchParams.set(key,value);return u.href;}
export function filterRecords(records,state){const terms=normalizeSearch(state.query).split(' ').filter(Boolean);return records.filter(r=>r.layer===state.layer&&(!state.category||r.raw?.category===state.category)&&(!state.district||r.districtKeys.includes(state.district))&&(r.layer!=='projects'||!state.stage||r.stageKey===state.stage)&&terms.every(term=>normalizeSearch([r.name,r.nameHe,r.locality,r.id,r.planNumber,r.district,...r.districtKeys.flatMap(k=>districtLabels[k]||[k]),...(r.raw?.aliases||[]),r.raw?.category,r.raw?.categoryLabel,r.raw?.authorityCode,r.raw?.crop,r.raw?.cropEnglish,r.raw?.sourceParcelId,r.raw?.sourceFeatureId].join(' ')).includes(term)));}
export function exportRecords(records,registry={},provenance=null,base='https://spfi.invalid/agripv/',extra={}){
 const sources=(registry.sources||[]).filter(s=>s.visibility==='public');
 return {type:'FeatureCollection',schemaVersion:1,generatedAt:new Date().toISOString(),provenance:provenance||null,features:records.map(r=>{
 const claims=r.layer==='projects'?publicClaims(r.raw):[];const used=new Set(claims.flatMap(c=>(c.evidence||[]).map(e=>e.sourceId)));
 const refs=sources.filter(s=>used.has(s.sourceId)).map(s=>({id:s.sourceId,title:s.title,url:safeURL(s.url),publishedAt:s.publicationDate??s.publishedAt??null}));
 const outcome=r.layer==='projects'?extra.outcomes?.projects?.find(p=>p.projectId===r.id):null;const watch=r.layer==='plans'?extra.spatial?.records?.find(p=>'plan-'+p.officialPlanId===r.id):null;const c=stageClaim(r.raw||{});const limitations=r.layer==='projects'?[...(r.raw.dataGaps||[]),'A reported stage is dated evidence, not live operating status.']:r.layer==='plans'?['Official planning status does not establish construction or operation.']:r.layer==='industrial'?['Official authority-level aggregate, not individual roof footprints. Grid feasibility is not established.']:r.layer==='public'?['Official modelled potential, not measured generation or a confirmed project.',r.raw.usageRestriction||'Survey of Israel copyright; not for commercial use.']:['Sample parcel; technical suitability, land rights, permits and grid connection are not established.'];
 return {type:'Feature',geometry:r.geometryValid?r.geometry:null,properties:{reportedResults:outcome?{observations:outcome.observations,dataGaps:outcome.dataGaps,impactReadiness:outcome.impactReadiness}:null,constructionWatch:watch?.constructionWatch||null,snapshotId:['candidates','industrial','public'].includes(r.layer)?provenance?.potentialSnapshot||null:null,datasetReviewedAt:r.layer==='projects'?provenance?.reviewedAt||null:null,planningSourceUpdatedAt:r.layer==='plans'?provenance?.planningSourceLastEditAt||null:null,planNumber:r.planNumber||null,category:r.raw?.category||null,modelledCapacityKw:r.raw?.capacityEstimateKw??null,modelledCapacityMw:r.raw?.capacityEstimateMw??null,modelledAnnualGenerationKwh:r.raw?.annualGenerationKwh??null,crop:r.raw?.crop||null,areaDunam:r.area??r.raw?.areaDunam??null,id:r.id,name:r.name,nameHe:r.nameHe||null,layer:r.layer,locality:r.locality||null,district:r.district||null,officialPlanningStatus:r.layer==='plans'?r.stage||null:null,reportedProjectStage:r.layer==='projects'?r.stage||null:null,stageEvidenceDated:c?.observedAt||null,recordReviewed:c?.checkedAt||null,sourceObservationDated:r.layer==='plans'?r.date:r.raw?.sourceUpdatedAt||null,locationPrecision:r.layer==='projects'?'Representative point; not a surveyed site boundary.':'Source polygon; not a land-rights determination.',geometryAvailable:r.geometryValid,sources:r.layer==='projects'?refs:r.url?[{url:r.url}]:[],claims:claims.map(c=>({id:c.claimId,property:c.property,value:c.value??null,evidenceStatus:c.evidenceStatus,observedAt:c.observedAt||null,checkedAt:c.checkedAt||null,explanation:c.explanation,sourceIds:(c.evidence||[]).map(e=>e.sourceId).filter(id=>refs.some(s=>s.id===id))})),limitations,recordURL:stateURL(base,{lang:'en',layer:r.layer,record:r.id})}};
 })};
}
export function exportCSV(collection){const keys=['reportedResults','constructionWatch','snapshotId','datasetReviewedAt','planningSourceUpdatedAt','planNumber','category','modelledCapacityKw','modelledCapacityMw','modelledAnnualGenerationKwh','crop','areaDunam','id','name','layer','locality','district','officialPlanningStatus','reportedProjectStage','stageEvidenceDated','recordReviewed','sourceObservationDated','locationPrecision','geometryAvailable','sources','claims','limitations','recordURL'];const cell=v=>{let s=typeof v==='object'&&v!==null?JSON.stringify(v):String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return '\uFEFF'+[keys.map(cell).join(','),...collection.features.map(f=>keys.map(k=>cell(f.properties[k])).join(','))].join('\r\n');}

export function geometryExtent(geometry){const points=geometry.type==='Point'?[geometry.coordinates]:geometry.type==='Polygon'?geometry.coordinates.flat():geometry.coordinates.flat(2);let west=180,south=90,east=-180,north=-90;for(const [x,y] of points){west=Math.min(west,x);south=Math.min(south,y);east=Math.max(east,x);north=Math.max(north,y);}return [west,south,east,north];}
export function intersects(a,b){return !!a&&!!b&&a[0]<=b[2]&&a[2]>=b[0]&&a[1]<=b[3]&&a[3]>=b[1];}
