import {bindSearch} from './site-search.js';
import {readerPages} from './reader-pages.js';
import {bindMobileNavigation} from './mobile-navigation.js';
import {articleExtras} from './article-extras.js';
import {magazinePage} from './magazine-page.js';
import {editorialPages,editorialHref,articleHref} from './editorial-pages.js';
import {comparisonLayout} from './comparison-layout.js';
import {deskDetails,deskHref} from './israel-sections.js';
import {bindHorizontalRails} from './horizontal-rails.js';
import {additionalActors} from './organisations.js';
import {sectionPages,sectionHref} from './section-pages.js';
import {articleGroups,groupDescriptions,groupsFor,matchesGroup} from './article-groups.js';
import {storyArt} from './photo-renderer.js';
import {sections} from './israel-sections.js';
import {renderArticleBody,bindArticleInteractions} from './article-reader.js';
import {actors,faqs,sources} from './content.js';
const text=(en,he)=>({en,he});
const words={nav:text(['Stories','Map','About'],['כתבות','מפה','אודות']),title:text('Solar knowledge.<br><em>For everyone.</em>','ידע סולארי.<br><em>בשביל כולם.</em>'),intro:text('The ideas, people and evidence shaping solar power in Israel. From the laboratory to the rooftop—and the field in between.','הרעיונות, האנשים והראיות שמעצבים את האנרגיה הסולארית בישראל. מהמעבדה לגג — ולשדה שביניהם.'),journal:text('Stories','כתבות'),journalSub:text('Solar, seen through projects, people, research, and everyday life.','השמש דרך פרויקטים, אנשים, מחקר וחיי היומיום.'),all:text('All stories','כל הכתבות'),read:text('Read the story','לקריאת הכתבה'),search:text('Search the journal…','חיפוש בכתבות…'),source:text('Sources and further reading','מקורות וקריאה נוספת'),checked:text('Source checked','המקור נבדק'),learn:text('A little clarity goes a long way.','קצת בהירות עושה הבדל גדול.'),people:text('Organisations working with solar','ארגונים העוסקים באנרגיה סולארית'),actorSub:text('Organisations in Israel and around the world. Explore their work through their own websites.','ארגונים בישראל ובעולם. הכירו את עבודתם דרך האתרים שלהם.'),visit:text('Visit organisation website ↗','לאתר הארגון ↖'),more:text('Show more stories','עוד כתבות'),none:text('No stories in this section yet. Explore another section from the navigation.','עדיין אין כתבות במדור הזה. בחרו מדור אחר בניווט.')};
const topics={all:words.all,agripv:text('Agrivoltaics','אגרו־וולטאיקה'),research:text('Research & technology','מחקר וטכנולוגיה'),industry:text('Industry & policy','תעשייה ומדיניות'),people:text('People & communities','אנשים וקהילות'),environment:text('Environment','סביבה'),storage:text('Storage & grids','אגירה ורשתות')};
let lang=new URLSearchParams(location.search).get('lang')==='he'?'he':'en';
try{if(!new URLSearchParams(location.search).has('lang'))lang=localStorage.getItem('spfi-language')==='he'?'he':'en';}catch{}
let stories=[],metadata={},topic=Object.hasOwn(sectionPages,document.documentElement.dataset.topic)?document.documentElement.dataset.topic:'all',section=Object.hasOwn(sections,document.documentElement.dataset.section)?document.documentElement.dataset.section:'all',limit=999,loadState='loading';
const t=x=>typeof x==='object'?x[lang]:x;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mapURL=()=>`${location.hostname==='spfi.co.il'?'https://agripv.spfi.co.il/':'./agripv/'}?lang=${lang}`;
const page=Object.hasOwn(editorialPages,document.documentElement.dataset.page)?document.documentElement.dataset.page:'';
const article=document.documentElement.dataset.article||'';
const isHome=()=>topic==='all'&&section==='all'&&!page&&!article;
let cleanupRails=()=>{};
let cleanupNavigation=()=>{};
const pageTitle=()=>article?(t(stories.find(s=>s.id===article)?.title||text('Story','כתבה'))+' — SPFI'):section!=='all'?t(sections[section])+' — SPFI':topic!=='all'?t(sectionPages[topic])+' — SPFI':page?t(editorialPages[page])+' — SPFI':t(text('SPFI — Solar Platform for Israel','SPFI — הפלטפורמה הסולארית של ישראל'));
const external=(url,label)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;
function render(){cleanupRails();cleanupNavigation();document.body.classList.add('magazine-version');document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';document.title=pageTitle();document.getElementById('app').innerHTML=`
 <div class="topline"><div class="wrap"><span>${t(text('SOLAR PLATFORM FOR ISRAEL','אנרגיה סולארית לישראל · ידע עצמאי'))}</span><span>${t(text('Solar, in context.','אנרגיה סולארית, בהקשר.'))}</span></div></div>
 <header><div class="wrap header-row"><a class="brand" href="./index.html?lang=${lang}" aria-label="SPFI home"><img src="./favicon.svg" alt="">SPFI<small>SOLAR PLATFORM<br>FOR ISRAEL</small></a><nav class="nav" aria-label="${t(text('Main navigation','ניווט ראשי'))}">${Object.entries(sectionPages).map(([id,page])=>`<a href="${sectionHref(id,lang)}" ${topic===id?'aria-current="page"':''}>${esc(t(page))}</a>`).join('')}<details class="mag-menu"><summary>${t(text('Israel Desk','ישראל מקרוב'))}</summary><div>${Object.entries(sections).map(([id,name])=>`<a href="${deskHref(id,lang)}" ${section===id?'aria-current="page"':''}>${esc(t(name))}</a>`).join('')}</div></details></nav><a class="site-search-link" href="./search.html?lang=${lang}" aria-label="${lang==='he'?'חיפוש ב־SPFI':'Search SPFI'}">⌕ <span>${lang==='he'?'חיפוש':'Search'}</span></a><div class="language" aria-label="Language"><button data-lang="en" class="${lang==='en'?'active':''}" aria-pressed="${lang==='en'}">EN</button><button data-lang="he" class="${lang==='he'?'active':''}" aria-pressed="${lang==='he'}">עברית</button></div></div><nav class="mag-submenu wrap" aria-label="${t(text('Editorial sections','מדורי מערכת'))}">${[['latest','Latest news','חדשות אחרונות'],['opinion','Opinion and Analysis','דעה וניתוח'],['sponsored','Sponsored','תוכן ממומן'],['press','Press Release','הודעות לעיתונות'],['popular','Most Popular','הכתבות הפופולריות'],['learn','Solar, explained','סולארי, בפשטות']].map(([id,en,he])=>`<a href="${editorialHref(id,lang)}" ${page===id?'aria-current="page"':''}>${t(text(en,he))}</a>`).join('')}<a href="${mapURL()}">AGRIPV / ISRAEL ↗</a></nav></header>
 <main id="main" class="wrap">${isHome()?comparisonLayout(stories,metadata,lang):magazinePage(stories,metadata,lang,{topic,section,page,article,state:loadState})}
 ${isHome()||page==='learn'?`<section class="section two-col"><div class="learning" id="learn">${storyArt('government-solar-calculator-guide',lang,'section')}<div class="eyebrow">${t(text('SOLAR, EXPLAINED','סולארי, בפשטות'))}</div><h2 style="margin-top:18px">${t(words.learn)}</h2>${faqs.map(([q,a,s])=>`<details><summary>${t(q)}</summary><p>${t(a)}</p>${s?external(sources[s].url,sources[s].name):`<a href="${mapURL()}">${t(text('Explore the evidence map ↗','למפת הראיות ↖'))}</a>`}</details>`).join('')}</div><div class="map-promo"><div class="eyebrow">AGRIPV / ISRAEL</div><h2>${t(text('Find the places behind the stories','המקומות שמאחורי הסיפורים'))}</h2><p>${t(text('Explore agrivoltaic plans, reviewed projects and potential agricultural sites. See what is known—and what still needs checking.','גלו תוכניות אגרו־וולטאיות, פרויקטים שנבדקו ושטחים חקלאיים פוטנציאליים. ראו מה ידוע — ומה עדיין דורש בדיקה.'))}</p><a class="btn" href="${mapURL()}">${t(text('Explore the map','למפה'))} ↗</a><p class="minor">${t(text('Coverage is growing. An empty area does not necessarily mean there is no solar activity.','הכיסוי מתרחב. אזור ריק אינו מעיד בהכרח שאין בו פעילות סולארית.'))}</p><div class="map-counts"><div><strong>92</strong><span>${t(text('planning records','רשומות תכנון'))}</span></div><div><strong>9</strong><span>${t(text('reviewed projects','פרויקטים שנבדקו'))}</span></div><div><strong>500</strong><span>${t(text('candidate parcels','חלקות לבדיקה'))}</span></div><p class="minor">${t(text('Imported snapshots · Aug–Sep 2026','נתונים מיובאים · אוגוסט–ספטמבר 2026'))}</p></div></div></section>
 `:''}
 ${isHome()||page==='organisations'?`<section class="section" id="people"><div class="section-head"><div><h2>${t(words.people)}</h2><p>${t(words.actorSub)}</p></div></div><div class="rail-controls"><button class="btn light" data-org-step="-1" aria-controls="organisation-rail">${t(text('Previous','הקודם'))}</button><button class="btn light" id="organisation-motion" aria-controls="organisation-rail">${t(text('Pause scrolling','השהיית גלילה'))}</button><button class="btn light" data-org-step="1" aria-controls="organisation-rail">${t(text('Next','הבא'))}</button></div><div class="actors organisation-rail" id="organisation-rail" tabindex="0" role="region" aria-label="${t(words.people)}">${[...actors,...additionalActors].map(a=>`<article class="actor" dir="${lang==='he'?'rtl':'ltr'}"><span class="tag">${t(a.role)}</span><h3>${t(a.name)}</h3><p>${t(a.text)}</p>${external(a.url||sources[a.source].url,t(words.visit))}</article>`).join('')}</div></section>
 `:''}
 ${isHome()||page==='about'?`<section class="section editorial" id="about"><h2>${t(text('Curious about possibilities. Careful with claims.','סקרנים לגבי האפשרויות. זהירים לגבי הטענות.'))}</h2><div><p>${t(text('SPFI is an independent educational publication. We select useful stories, read the original reporting or research, and write our own English and Hebrew explanations. Telegram helps us discover stories; it is not proof of a claim.','SPFI הוא פרסום חינוכי עצמאי. אנו בוחרים סיפורים שימושיים, קוראים את הדיווח או המחקר המקורי וכותבים הסברים משלנו באנגלית ובעברית. טלגרם עוזר לגלות סיפורים; הוא אינו הוכחה לטענה.'))}</p><p>${t(text('Research findings, company claims and editorial interpretation are distinguished. Historical reports keep their dates. Mentioning an organization does not imply a partnership or endorsement.','אנו מבחינים בין ממצאי מחקר, טענות חברות ופרשנות מערכתית. דיווחים היסטוריים שומרים על התאריך שלהם. אזכור ארגון אינו מעיד על שותפות או המלצה.'))}</p><a href="./corrections.html?lang=${lang}">${t(text('Suggest a correction or a story ↗','הציעו תיקון או סיפור ↖'))}</a></div></section>
 `:''}
 </main><footer class="wrap"><div class="footer-row"><a class="brand" href="./index.html?lang=${lang}">☼ SPFI</a><p>${t(text('Stories, places, and evidence from the world of solar.','סיפורים, מקומות וראיות מעולם האנרגיה הסולארית.'))}<br><a href="./about.html?lang=${lang}">${t(text('About','אודות'))}</a> · <a href="./organisations.html?lang=${lang}">${t(text('Organisations','ארגונים'))}</a> · ${Object.entries(readerPages).map(([id,name])=>`<a href="./${id}.html?lang=${lang}">${esc(t(name))}</a>`).join(' · ')} · <a href="https://github.com/dima-jd/spfi">GitHub</a> · <a href="${mapURL()}">AGRIPV</a></p></div></footer>`;
 document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;try{localStorage.setItem('spfi-language',lang);}catch{}const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u);render();const active=article||new URLSearchParams(location.search).get('article');if(active)openStory(active);});
 cleanupNavigation=bindMobileNavigation(document.getElementById('app'),lang);
 bindStoryLinks();
 bindSearch(document.getElementById('app'),lang);
 cleanupRails=bindHorizontalRails(document.getElementById('app'),lang);
}
function bindStoryLinks(){document.querySelectorAll('[data-story]').forEach(b=>b.onclick=e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();openStory(b.dataset.story);});}
function openStory(id,navigate=true){const s=stories.find(s=>s.id===id);if(!s)return;const refs=(s.sources||[]).map(k=>typeof k==='string'?sources[k]:k).filter(Boolean);const target=document.getElementById(article?'article-page-content':'reader-content');if(!target)return;target.innerHTML=`<div class="reader-toolbar"><a href="./index.html?lang=${lang}" id="reader-back">${t(text("← Back to SPFI","חזרה ל־SPFI →"))}</a><div class="language"><button data-reader-lang="en" aria-pressed="${lang==='en'}">EN</button><button data-reader-lang="he" aria-pressed="${lang==='he'}">עברית</button></div></div><span class="tag">${t(topics[s.topic])}</span>${groupsFor(metadata[s.id]).map(id=>`<span class="tag">${esc(t(articleGroups[id]))}</span>`).join('')}<h1 id="reader-title" class="reader-title">${esc(t(s.title))}</h1>${groupsFor(metadata[s.id]).filter(id=>id!=='secondary').map(id=>`<p class="minor">${esc(t(groupDescriptions[id]))}</p>`).join('')}<p class="reader-lead">${esc(t(s.excerpt))}</p>${s.date?`<p class="minor">${t(text('Source publication','פרסום המקור'))}: ${esc(s.date)}</p>`:''}${storyArt(s.id,lang)}<div class="reader-copy">${renderArticleBody(s,lang)}</div><p><a href="./corrections.html?lang=${lang}">${t(text('Report a correction','דיווח על תיקון'))}</a></p><div class="source-links"><strong>${t(words.source)}</strong>${refs.map(r=>external(r.url,r.name)).join('')}${s.telegram?external(s.telegram,t(text('Discovered via Telegram','נמצא דרך טלגרם'))):''}<p class="minor">${t(text('SPFI editorial adaptation. Follow the original links for the full reporting and supporting evidence.','עיבוד מערכתי של SPFI. הדיווח המלא והראיות התומכות זמינים בקישורי המקור.'))}</p></div>`;if(article){const extras=articleExtras(s,stories,metadata,lang);target.innerHTML=`<div class="article-columns"><div class="article-main">${target.innerHTML}${extras.related}</div>${extras.sidebar}</div>`;}if(!article)document.getElementById('reader-back').onclick=e=>{e.preventDefault();dialog.close();};document.querySelectorAll('[data-reader-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.readerLang;try{localStorage.setItem('spfi-language',lang);}catch{}document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';render();openStory(id,false);});bindArticleInteractions(target,s,lang);if(article){const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u);document.title=t(s.title)+' — SPFI';return;}if(!document.getElementById('reader').open)document.getElementById('reader').showModal();document.getElementById('reader').scrollTop=0;const u=new URL(location.href);u.searchParams.set('article',id);u.searchParams.set('lang',lang);if(navigate&&new URLSearchParams(location.search).get('article')!==id)history.pushState({spfiReader:true},'',u);else history.replaceState(history.state,'',u);document.title=t(s.title)+' — SPFI';}
const dialog=document.getElementById('reader');document.getElementById('close-reader').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{const u=new URL(location.href);u.searchParams.delete('article');history.replaceState(null,'',u);document.title=pageTitle();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
render();
try{const [response,sectionResponse]=await Promise.all([fetch('./articles.json'),fetch('./article-sections.json')]);if(!response.ok||!sectionResponse.ok)throw Error('Content unavailable');stories=await response.json();metadata=await sectionResponse.json();loadState='ready';render();}catch{loadState='error';if(Object.hasOwn(readerPages,page))render();else document.getElementById('main').innerHTML='<p role="alert">'+t(text('Stories could not load. Reload to try again.','לא ניתן לטעון את הכתבות. נסו לרענן.'))+'</p>';}
const selected=article||new URLSearchParams(location.search).get('article');if(selected){if(stories.some(s=>s.id===selected))openStory(selected,false);else if(loadState==='ready')document.getElementById('main').innerHTML='<h1>'+t(text('This article is not available','הכתבה אינה זמינה'))+'</h1>';}
if(location.hash&&!selected)document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView();
window.addEventListener('popstate',()=>{const id=new URLSearchParams(location.search).get('article');if(id)openStory(id,false);else if(dialog.open)dialog.close();});
