import {storyArt} from './photo-renderer.js';
import {sections,deskDetails,deskHref} from './israel-sections.js';
export {sections} from './israel-sections.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function homeLayout(stories,meta,lang,topics,mapURL='./agripv/'){
 const t=x=>x?.[lang]||x?.en||'';
 const label=(en,he)=>lang==='he'?he:en;
 const pick=id=>stories.find(s=>s.id===id);
 const card=s=>!s?'':`<article class="news-card"><span class="tag">${esc(t(sections[meta[s.id]?.section]||topics[s.topic]))}</span><h3><a data-story="${s.id}" href="?lang=${lang}&article=${s.id}">${esc(t(s.title))}</a></h3><p>${esc(t(s.excerpt))}</p></article>`;
 const lead=pick('israel-100000-solar-roofs-programme')||stories[0];
 return `<section class="home-hero full-bleed" aria-labelledby="front-title">${storyArt('israel-2030-renewable-electricity-target',lang,'lead')}<div class="hero-copy"><span class="eyebrow">SPFI · ${label('SOLAR PLATFORM FOR ISRAEL','הפלטפורמה הסולארית של ישראל')}</span><h1 id="front-title">${label('Solar,<br>in context.','אנרגיה סולארית,<br>בהקשר.')}</h1><p>${label('Explore the projects, people, and ideas shaping how solar becomes part of our landscapes and everyday lives.','גלו את הפרויקטים, האנשים והרעיונות שמעצבים את השתלבות האנרגיה הסולארית בנוף ובחיי היומיום שלנו.')}</p><div class="hero-actions"><a class="btn" href="${esc(mapURL)}">${label('Explore the map','למפה')}</a><a class="btn light" href="#journal">${label('Read the stories','לקריאת הכתבות')}</a></div><small>${label('Rooted in Israel. Connected to a wider world.','שורשים בישראל. חיבור לעולם הרחב.')}</small></div></section>
 <section class="frontpage"><div class="section-head"><h2>${label('A closer look at solar','מבט מקרוב על אנרגיה סולארית')}</h2></div><div class="featured-stories">${[lead,pick('maale-gilboa-grapes-first-season'),pick('huji-printing-solar-windows')].map(card).join('')}</div></section>
 <section class="israel-desk" id="israel" aria-labelledby="desk-title"><div class="section-head"><div><span class="eyebrow" id="desk-title">${label('THE ISRAEL DESK','ישראל מקרוב')}</span><h2>${label('Five ways into the story.','חמש דרכים להכיר את הסיפור.')}</h2></div><div class="rail-controls"><button class="btn light" data-desk-step="-1" aria-controls="desk-rail">${label('Previous','הקודם')}</button><button class="btn light" data-desk-step="1" aria-controls="desk-rail">${label('Next','הבא')}</button></div></div><nav class="desk-nav" aria-label="${label('Israel sections','מדורי ישראל')}">${Object.entries(sections).map(([id,name])=>`<a href="${deskHref(id,lang)}">${esc(t(name))}</a>`).join('')}</nav><div class="desk-rail full-bleed" id="desk-rail" tabindex="0" role="region" aria-label="${label('Israel Desk — scroll horizontally','ישראל מקרוב — גלילה אופקית')}">${Object.entries(sections).map(([id,name],i)=>{const count=stories.filter(s=>meta[s.id]?.section===id).length;return `<section class="desk-panel" id="${id}" aria-labelledby="title-${id}">${storyArt(deskDetails[id].image,lang,'desk')}<div class="desk-panel-copy"><span class="desk-number">0${i+1} / 05</span><h2 id="title-${id}">${esc(t(name))}</h2><p>${esc(t(deskDetails[id]))}</p><a class="btn" href="${deskHref(id,lang)}">${label('Explore the section','למדור')} <span>↗</span></a><small>${count} ${label('articles','כתבות')}</small></div></section>`;}).join('')}</div></section>`;
}
