// Official organisation pages reviewed 2026-09-21. Descriptions identify fields of work, not rankings or endorsements.
const bi=(en,he)=>({en,he});
const rows=[
 ['SolarEdge','סולאראדג׳','Solar electronics','אלקטרוניקה סולארית','Solar inverters, power optimisation and energy management.','ממירים סולאריים, אופטימיזציה של הספק וניהול אנרגיה.','https://www.solaredge.com/us/'],
 ['Enlight Renewable Energy','אנלייט אנרגיה מתחדשת','Development','פיתוח פרויקטים','Develops renewable-energy projects across solar, wind and storage.','מפתחת פרויקטים באנרגיה מתחדשת בתחומי השמש, הרוח והאגירה.','https://enlightenergy.com/'],
 ['Nofar Energy','נופר אנרגיה','Solar & storage','שמש ואגירה','Develops solar and energy-storage projects in several markets.','מפתחת פרויקטים סולאריים ופרויקטי אגירה במספר שווקים.','https://www.nofar-energy.com/'],
 ['Ecoppia','אקופיה','Operations','תפעול','Develops robotic cleaning systems for solar panels.','מפתחת מערכות ניקוי רובוטיות לפאנלים סולאריים.','https://www.ecoppia.com/'],
 ['Econergy','אקונרג׳י','Development','פיתוח פרויקטים','Develops, owns and operates renewable-energy projects, including solar and storage.','מפתחת, מחזיקה ומפעילה פרויקטים באנרגיה מתחדשת, ובהם שמש ואגירה.','https://www.econergytech.com/'],
 ['Fraunhofer ISE','פראונהופר ISE','Research','מחקר','Researches solar cells, integrated photovoltaics and energy systems.','חוקר תאים סולאריים, מערכות פוטו־וולטאיות משולבות ומערכות אנרגיה.','https://www.ise.fraunhofer.de/en.html'],
 ['Helmholtz-Zentrum Berlin','מרכז הלמהולץ ברלין','Materials research','מחקר חומרים','Researches solar-energy materials, including perovskite and tandem cells.','חוקר חומרים לאנרגיה סולארית, לרבות תאי פרובסקיט וטנדם.','https://www.helmholtz-berlin.de/index_en.html'],
 ['CSEM','CSEM','Applied research','מחקר יישומי','Works on solar cells, modules and integrated photovoltaics.','עוסק בתאים ובמודולים סולאריים ובפוטו־וולטאיקה משולבת.','https://www.csem.ch/en/'],
 ['pv magazine','pv magazine','Solar journalism','עיתונות סולארית','Publishes reporting on photovoltaic technology, industry and markets.','מפרסם דיווחים על טכנולוגיה פוטו־וולטאית, התעשייה והשווקים.','https://www.pv-magazine.com/'],
 ['SolarPower Europe','SolarPower Europe','Industry association','איגוד ענפי','Represents the European solar sector and publishes market and policy work.','מייצג את הענף הסולארי באירופה ומפרסם עבודות בנושאי שוק ומדיניות.','https://www.solarpowereurope.org/'],
 ['IEA PVPS','IEA PVPS','Research cooperation','שיתוף פעולה מחקרי','An international programme sharing photovoltaic research and analysis.','תוכנית בינלאומית לשיתוף מחקר וניתוח בתחום הפוטו־וולטאיקה.','https://iea-pvps.org/'],
 ['First Solar','First Solar','Module manufacturing','ייצור מודולים','Manufactures cadmium-telluride thin-film photovoltaic modules.','מייצרת מודולים פוטו־וולטאיים בשכבה דקה מקדמיום־טלוריד.','https://www.firstsolar.com/en-EMEA/'],
 ['SMA Solar Technology','SMA Solar Technology','Inverters & systems','ממירים ומערכות','Supplies solar and battery inverters and energy-management systems.','מספקת ממירים סולאריים, ממירי סוללות ומערכות לניהול אנרגיה.','https://www.sma.de/en/'],
 ['Trinasolar','טרינה סולאר','Solar manufacturing','ייצור סולארי','Develops photovoltaic modules and solar-energy solutions.','מפתחת מודולים פוטו־וולטאיים ופתרונות לאנרגיה סולארית.','https://www.trinasolar.com/en-glb/'],
 ['JinkoSolar','ג׳ינקו סולאר','Solar manufacturing','ייצור סולארי','Manufactures photovoltaic products for solar installations.','מייצרת מוצרים פוטו־וולטאיים למתקנים סולאריים.','https://www.jinkosolar.com/en/'],
 ['LONGi','לונג׳י','Solar manufacturing','ייצור סולארי','Develops and manufactures photovoltaic cells and modules.','מפתחת ומייצרת תאים ומודולים פוטו־וולטאיים.','https://www.longi.com/en/'],
 ['Canadian Solar','קנדיאן סולאר','Solar & storage','שמש ואגירה','Works in solar modules, project development and energy storage.','עוסקת במודולים סולאריים, בפיתוח פרויקטים ובאגירת אנרגיה.','https://www.canadiansolar.com/'],
 ['Oxford PV','Oxford PV','Tandem photovoltaics','פוטו־וולטאיקה בטנדם','Develops perovskite-on-silicon tandem solar technology.','מפתחת טכנולוגיה סולארית בטנדם המשלבת פרובסקיט וסיליקון.','https://www.oxfordpv.com/'],
 ['BayWa r.e.','BayWa r.e.','Renewable-energy projects','פרויקטים באנרגיה מתחדשת','Works in renewable-energy development and solar services.','עוסקת בפיתוח אנרגיה מתחדשת ובשירותים סולאריים.','https://www.baywa-re.com/en'],
 ['Statkraft','סטטקראפט','Renewable-energy projects','פרויקטים באנרגיה מתחדשת','Develops renewable-energy assets, including solar projects.','מפתחת מתקנים באנרגיה מתחדשת, ובהם פרויקטים סולאריים.','https://www.statkraft.com/'],
 ['Akuo','אקואו','Renewable-energy projects','פרויקטים באנרגיה מתחדשת','A renewable-energy producer working across solar and other technologies.','יצרנית אנרגיה מתחדשת העוסקת באנרגיה סולארית ובטכנולוגיות נוספות.','https://www.akuoenergy.com/'],
 ['Solar Energy UK','Solar Energy UK','Industry association','איגוד ענפי','Represents solar and storage businesses in the United Kingdom.','מייצג עסקים בתחומי השמש והאגירה בבריטניה.','https://solarenergyuk.org/'],
 ['NCAT · AgriSolar Clearinghouse','NCAT · AgriSolar Clearinghouse','Farming & knowledge','חקלאות וידע','Connects people and resources around agriculture and solar on shared land.','מחבר בין אנשים ומשאבי ידע בנושאי חקלאות ואנרגיה סולארית באותה קרקע.','https://www.ncat.org/clean-energy-and-conservation/agrisolar-clearinghouse/'],
 ['Solar United Neighbors','Solar United Neighbors','Community solar','שמש וקהילה','Helps people and communities explore and advocate for solar energy.','מסייע לאנשים ולקהילות להכיר אנרגיה סולארית ולפעול לקידומה.','https://solarunitedneighbors.org/'],
 ['US DOE · Integrated Energy Systems Office','משרד האנרגיה האמריקאי · המשרד למערכות אנרגיה משולבות','Public research','מחקר ציבורי','Supports research in advanced photovoltaics, solar thermal systems and grid integration.','תומך במחקר בפוטו־וולטאיקה מתקדמת, במערכות תרמו־סולאריות ובשילוב ברשת.','https://www.energy.gov/cmei/systems/integrated-energy-systems-office']
];
export const additionalActors=rows.map(([en,he,roleEn,roleHe,textEn,textHe,url])=>({name:bi(en,he),role:bi(roleEn,roleHe),text:bi(textEn,textHe),url,checkedAt:'2026-09-21'}));
