import {readerConfig} from './reader-config.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const readerPages={search:{en:'Search SPFI',he:'חיפוש ב־SPFI'},newsletter:{en:'Newsletter',he:'ניוזלטר'},methods:{en:'Methods',he:'שיטות העבודה'},contact:{en:'Contact SPFI',he:'יצירת קשר'},corrections:{en:'Corrections',he:'תיקונים'},privacy:{en:'Privacy',he:'פרטיות'},accessibility:{en:'Accessibility',he:'נגישות'}};
const copy={
 methods:[
 ['How we build a story','איך נבנית כתבה','We select reporting, research and announcements, check the available original sources, and write original English and Hebrew explanations. Discovery links are leads, not evidence. Sources appear beside the article so readers can examine the underlying claims.','אנו בוחרים דיווחים, מחקרים והודעות, בודקים את המקורות המקוריים הזמינים וכותבים הסברים מקוריים באנגלית ובעברית. קישורי גילוי הם כיווני מחקר, לא ראיות. המקורות מוצגים לצד הכתבה כדי לאפשר בחינה של הטענות.'],
 ['What the evidence supports','מה הראיות תומכות בו','Company claims, laboratory findings, projections and editorial interpretation are attributed and distinguished. A proposal is not a completed installation; a completed installation does not prove a particular outcome. Missing information stays visible.','טענות חברות, ממצאי מעבדה, תחזיות ופרשנות מערכתית מיוחסים למקור ומובחנים זה מזה. הצעה אינה מתקן שהושלם; מתקן שהושלם אינו הוכחה לתוצאה מסוימת. מידע חסר נשאר גלוי.'],
 ['How to read the map','איך לקרוא את המפה','The current map separates reviewed projects, official planning records, a sample of 500 agricultural parcels, industrial authority aggregates and public-area modelled potential. It is a dated snapshot, not a live operating feed. Planning status does not establish construction. Screening does not establish technical suitability, land rights or grid access.','המפה הנוכחית מפרידה בין פרויקטים שנבדקו, רשומות תכנון רשמיות, מדגם של 500 חלקות חקלאיות, נתונים תעשייתיים מצרפיים של רשויות ופוטנציאל מחושב בשטח ציבורי. זו תמונת מצב מתוארכת, לא עדכון תפעולי חי. סטטוס תכנוני אינו מוכיח בנייה. סינון אינו קובע התאמה טכנית, זכויות בקרקע או גישה לרשת.'],
 ['Dates and editorial placement','תאריכים ובחירה מערכתית','Source publication dates, observation dates and record reviews describe different events. Trending and promoted selections are chosen by SPFI; they are not readership rankings or paid sponsorship. Urgent posts are editorial priorities, not breaking-news alerts.','תאריכי פרסום מקור, תצפית ובדיקת רשומה מתארים אירועים שונים. כתבות חמות ומקודמות נבחרות בידי SPFI; אין מדובר בדירוגי קריאה או בחסות בתשלום. כתבות בעדיפות אינן התרעות על חדשות מתפרצות.']
 ],
 corrections:[
 ['Help us correct the record','עזרו לנו לתקן את הרשומה','Include the article or project link, the exact detail that needs correcting, your proposed correction and a supporting source if available. Distinguish a factual correction from a different interpretation.','צרפו קישור לכתבה או לפרויקט, את הפרט המדויק שיש לתקן, את התיקון המוצע ומקור תומך אם קיים. הבדילו בין תיקון עובדתי לבין פרשנות שונה.'],
 ['Review before publication','בדיקה לפני פרסום','A correction request is a request for editorial review. It does not automatically change an article or a map record. Evidence may support a correction, a clarification or an explicit note that accounts conflict.','בקשת תיקון נשלחת לבדיקת המערכת. היא אינה משנה אוטומטית כתבה או רשומה במפה. הראיות עשויות לתמוך בתיקון, בהבהרה או בציון מפורש של סתירה בין מקורות.']
 ],
 contact:[
 ['Get in touch','דברו איתנו','Use the contact route below for editorial questions, research contributions, story ideas or a problem with the website. For a correction, include a link and the specific detail you want reviewed.','השתמשו בערוץ יצירת הקשר שלהלן לשאלות מערכתיות, תרומות מחקר, רעיונות לכתבות או תקלה באתר. לבקשת תיקון, צרפו קישור ואת הפרט שברצונכם לבדוק.']
 ],
 privacy:[
 ['Microsoft Clarity','Microsoft Clarity','SPFI sends Microsoft Clarity only fixed event names and approved language and content categories through an isolated analytics frame. Clarity does not record the website content, forms, maps, uploaded documents or search URLs. Website session replay and heatmaps are disabled by this design. Microsoft may receive device and connection information.','SPFI שולח ל־Microsoft Clarity רק שמות אירועים קבועים וקטגוריות מאושרות של שפה ותוכן דרך מסגרת מדידה מבודדת. Clarity אינו מקליט את תוכן האתר, הטפסים, המפות, המסמכים שהועלו או כתובות החיפוש. הקלטות שימוש ומפות חום של האתר אינן מופעלות בתצורה זו. Microsoft עשויה לקבל מידע על המכשיר והחיבור.'],
 ['Website analytics','מדידת השימוש באתר','SPFI uses Google Analytics to understand article reading and use of the public map. Analytics may use cookies and receive device and connection information. Our event tracking sends only public content identifiers and limited categories such as language and district. It excludes search terms, form contents, contact details, private farmer information, uploaded documents and precise coordinates.','SPFI משתמש ב־Google Analytics להבנת הקריאה בכתבות והשימוש במפה הציבורית. השירות עשוי להשתמש בעוגיות ולקבל מידע על המכשיר והחיבור. מדידת האירועים שלנו שולחת רק מזהי תוכן ציבורי וקטגוריות מוגבלות כגון שפה ומחוז. היא אינה שולחת מילות חיפוש, תוכן טפסים, פרטי קשר, מידע פרטי על חקלאים, מסמכים שהועלו או קואורדינטות מדויקות.'],
 ['Search and preferences','חיפוש והעדפות','Site search runs in your browser against a downloaded public index. Search terms appear in the page URL, so avoid including private information in a search or a shared link. Your language preference is saved in browser local storage. You can remove it through your browser’s site-data settings.','החיפוש באתר מתבצע בדפדפן מול אינדקס ציבורי שמורד למכשיר. מילות החיפוש מופיעות בכתובת העמוד; הימנעו מהכללת מידע פרטי בחיפוש או בקישור משותף. העדפת השפה נשמרת באחסון המקומי של הדפדפן. ניתן למחוק אותה בהגדרות נתוני האתר בדפדפן.'],
 ['External services','שירותים חיצוניים','Pages may load photographs from Unsplash, fonts from external font services, and map resources from unpkg and OpenStreetMap. Those requests disclose connection information such as your IP address to the relevant service. External source links and GitHub have their own privacy practices. Hosting services may keep request logs.','עמודים עשויים לטעון תמונות מ־Unsplash, גופנים משירותים חיצוניים ומשאבי מפה מ־unpkg ומ־OpenStreetMap. בקשות אלה חושפות לשירות הרלוונטי פרטי חיבור כגון כתובת IP. לקישורי מקורות חיצוניים ול־GitHub יש נהלי פרטיות משלהם. שירותי אחסון עשויים לשמור יומני בקשות.'],
 ['Contact and newsletter','יצירת קשר וניוזלטר','GitHub issues are public. Do not include personal contact details, confidential project material or private field observations there. Newsletter registration becomes available only when a subscription service is connected; its signup page must explain the email use and cancellation route. This website does not currently collect newsletter email addresses.','פניות ב־GitHub הן ציבוריות. אל תכללו בהן פרטי קשר אישיים, חומר פרויקט חסוי או תצפיות שדה פרטיות. הרשמה לניוזלטר תהיה זמינה לאחר חיבור שירות הרשמה; עמוד ההרשמה צריך להסביר את השימוש בדוא״ל ואת דרך הביטול. אתר זה אינו אוסף כעת כתובות דוא״ל לניוזלטר.']
 ],
 accessibility:[
 ['Using SPFI','שימוש ב־SPFI','Use the Skip to content link to move past navigation. On small screens, separate buttons open the main menu and editorial sections. Keyboard users can move through links and controls with Tab; Escape closes article and map dialogs. The map has a list alternative.','השתמשו בקישור הדילוג לתוכן כדי לעבור את הניווט. במסכים קטנים, כפתורים נפרדים פותחים את התפריט הראשי ואת מדורי המערכת. ניתן לעבור בין קישורים ובקרים באמצעות Tab; מקש Escape סוגר חלוניות כתבה ומפה. למפה יש חלופת רשימה.'],
 ['Language and motion','שפה ותנועה','English and Hebrew controls set the reading direction. Some imported evidence remains in its source language. The organisations carousel has a pause control. Browser zoom and reduced-motion preferences can help tailor the reading experience.','בקרי אנגלית ועברית קובעים את כיוון הקריאה. חלק מהראיות המיובאות נשארות בשפת המקור. לרשימת הארגונים הנגללת יש כפתור השהיה. הגדלה בדפדפן והעדפת תנועה מופחתת יכולות להתאים את חוויית הקריאה.'],
 ['Known limits and feedback','מגבלות ומשוב','Accessibility work is ongoing; this page is not a claim of audited standards compliance. External documents and map tiles may have limitations we cannot control. Report the page URL, affected control, browser and assistive technology where relevant, and the task you could not complete.','העבודה על הנגישות נמשכת; עמוד זה אינו הצהרה על עמידה בתקן שנבדקה בביקורת. למסמכים חיצוניים ולאריחי מפה עשויות להיות מגבלות שאינן בשליטתנו. דווחו על כתובת העמוד, הבקר הבעייתי, הדפדפן והטכנולוגיה המסייעת אם רלוונטי, ועל הפעולה שלא הצלחתם להשלים.']
 ]};
export function newsletterHTML(lang='en'){const t=(a,b)=>lang==='he'?b:a;let url;try{const u=new URL(readerConfig.newsletterSignupURL);if(u.protocol==='https:')url=u.href;}catch{}return `<div class="newsletter-registration"><p>${t('Selected stories, project updates, and questions worth following.','כתבות נבחרות, עדכוני פרויקטים ושאלות שכדאי לעקוב אחריהן.')}</p>${url?`<a class="btn" href="${esc(url)}">${t('Register for the newsletter','הרשמה לניוזלטר')}</a>`:`<p class="newsletter-status">${t('Registration is not available yet. No subscription service is connected.','ההרשמה עדיין אינה זמינה. לא חובר שירות הרשמה.')}</p>`}<p><a href="./privacy.html?lang=${lang}">${t('Privacy information','מידע על פרטיות')}</a></p></div>`;}
export function readerPage(page,lang='en'){const t=(a,b)=>lang==='he'?b:a;if(page==='search')return `<section class="reader-service"><form data-clarity-mask="true" id="site-search" action="./search.html" method="get"><input type="hidden" name="lang" value="${lang}"><label for="site-query">${t('Search SPFI','חיפוש ב־SPFI')}</label><div class="search-row"><input id="site-query" name="q" type="search" placeholder="${t('Stories, projects, organisations or topics','כתבות, פרויקטים, ארגונים או נושאים')}"><button class="btn" type="submit">${t('Search','חיפוש')}</button></div><label for="search-category">${t('Results category','סוג תוצאה')}</label><select id="search-category" name="category">${[['all','All results','כל התוצאות'],['stories','Stories','כתבות'],['projects','Projects & map records','פרויקטים ורשומות מפה'],['organisations','Organisations','ארגונים'],['pages','Pages','עמודים']].map(([v,a,b])=>`<option value="${v}">${t(a,b)}</option>`).join('')}</select></form><div id="search-results" aria-live="polite"></div></section>`;if(page==='newsletter')return `<section class="reader-service">${newsletterHTML(lang)}</section>`;return `<section class="reader-service">${(copy[page]||[]).map(([a,b,c,d])=>`<h2>${t(a,b)}</h2><p>${t(c,d)}</p>`).join('')}${['contact','corrections','accessibility'].includes(page)?contactRoute(page,lang):''}${page==='methods'?`<p><a href="./agripv/?lang=${lang}">${t('Explore the evidence map','למפת הראיות')}</a> · <a href="./corrections.html?lang=${lang}">${t('Report a correction','דיווח על תיקון')}</a></p>`:''}</section>`;}
function contactRoute(page,lang){const t=(a,b)=>lang==='he'?b:a;const email=readerConfig.contactEmail;const subject=page==='corrections'?'SPFI correction':page==='accessibility'?'SPFI accessibility feedback':'SPFI editorial enquiry';const target=email&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?'mailto:'+email+'?subject='+encodeURIComponent(subject):'https://github.com/dima-jd/spfi/issues/new?title='+encodeURIComponent(subject);return `<p>${email?t('Send an email to the editorial contact.','שלחו דוא״ל לכתובת הקשר של המערכת.'):t('The current contact route is a public GitHub issue and requires a GitHub account. Do not include private information. A private editorial email address has not yet been configured.','ערוץ הקשר הנוכחי הוא פנייה ציבורית ב־GitHub, הדורשת חשבון GitHub. אל תכללו מידע פרטי. טרם הוגדרה כתובת דוא״ל פרטית למערכת.')}</p><a class="btn" href="${esc(target)}">${email?t('Email SPFI','שליחת דוא״ל ל־SPFI'):t('Open a public request on GitHub','פתיחת פנייה ציבורית ב־GitHub')}</a>`;}
